### ISSUE TITLE
Augment Library Metadata

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#64]
- [x] Permalink to swisscovery (https://github.com/zazuko/amos/issues/38#issuecomment-920756376)
- [x] GND links in the metadata which needs to extract data https://github.com/zazuko/amos/issues/38#issuecomment-999580491
- [ ] generate similar intervals as with the RIC-O data for a common search on dates #78 

8h
